### ISSUE TITLE
Error with run mix

### ISSUE THREAD

**Issue by raymand211092** [4DA/bleroma#3]
13:05:14.882 [info]  Application app exited: App.start(:normal, []) returned an error: shutdown: failed to start child: StateManager
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function Map.reject/2 is undefined or private
            (elixir) Map.reject(%{}, #Function<3.15186056/1 in StateManager.init/1>)
            (app) lib/app/state_manager.ex:56: StateManager.init/1
            (stdlib) gen_server.erl:374: :gen_server.init_it/2
            (stdlib) gen_server.erl:342: :gen_server.init_it/6
            (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3

13:05:14.883 [error] GenServer #PID<0.1869.0> terminating
** (UndefinedFunctionError) function Map.reject/2 is undefined or private
    (elixir) Map.reject(%{}, #Function<3.15186056/1 in StateManager.init/1>)
    (app) lib/app/state_manager.ex:56: StateManager.init/1
    (stdlib) gen_server.erl:374: :gen_server.init_it/2
    (stdlib) gen_server.erl:342: :gen_server.init_it/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #PID<0.1857.0>, {:undef, [{Map, :reject, [%{}, #Function<3.15186056/1 in StateManager.init/1>], []}, {StateManager, :init, 1, [file: 'lib/app/state_manager.ex', line: 56]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 374]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 342]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}}
State: {:state, {#PID<0.1869.0>, Supervisor.Default}, :one_for_one, {[Bleroma.DynamicSupervisor], %{Bleroma.DynamicSupervisor => {:child, #PID<0.1870.0>, Bleroma.DynamicSupervisor, {DynamicSupervisor, :start_link, [[strategy: :one_for_one, name: Bleroma.DynamicSupervisor]]}, :permanent, :infinity, :supervisor, [DynamicSupervisor]}}}, :undefined, 3, 5, [], 0, Supervisor.Default, {:ok, {%{intensity: 3, period: 5, strategy: :one_for_one}, [%{id: Bleroma.DynamicSupervisor, start: {DynamicSupervisor, :start_link, [[strategy: :one_for_one, name: Bleroma.DynamicSupervisor]]}, type: :supervisor}]}}}
** (Mix) Could not start application app: App.start(:normal, []) returned an error: shutdown: failed to start child: StateManager
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function Map.reject/2 is undefined or private
            (elixir) Map.reject(%{}, #Function<3.15186056/1 in StateManager.init/1>)
            (app) lib/app/state_manager.ex:56: StateManager.init/1
            (stdlib) gen_server.erl:374: :gen_server.init_it/2
            (stdlib) gen_server.erl:342: :gen_server.init_it/6
            (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3

**Comment by 4DA** [comment]
Hi, could you please say what erlang/elixir version are you using?

**Comment by raymand211092** [comment]
thanks for respond Elixir 1.9.1 (compiled with Erlang/OTP 22)

**Comment by 4DA** [comment]
Please try upgrading to newer version of Elixir.
Docs says Map.reject/2 is available since 1.13.0
